name: Update Excel File

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-excel:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Python 3.9.19
        run: |
          wget https://github.com/actions/python-versions/releases/download/3.9.19-9962534424/python-3.9.19-linux-22.04-x64.tar.gz

      - name: Extract Python 3.9.19 and List Contents
        run: |
          tar -xzf python-3.9.19-linux-22.04-x64.tar.gz
          ls -l  # List files to check the extracted contents
          find . -type d  # List directories to see where Python might be
